CREATE TABLE ARTICLE (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHORID INT,
    SLUG VARCHAR(255),
    TIME VARCHAR(255),
    ACTIVE BOOLEAN DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE POST_CATEGORY (
    ID INT AUTO_INCREMENT,
    POSTID VARCHAR(255) NOT NULL,
    CATEGORYID INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE POST_TAG (
    ID INT AUTO_INCREMENT,
    POSTID VARCHAR(255) NOT NULL,
    TAG VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE FILE (
    ID INT AUTO_INCREMENT,
    POSTID INT NOT NULL,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE USER (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE COMMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  POSTID INT NOT NULL,
  USERID INT NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  TIME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COMMENT_REPLY (
  ID INT NOT NULL AUTO_INCREMENT,
  COMMENTID INT NOT NULL,
  USERID INT NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  TIME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);